### PR TITLE
Fix for adding custom class

### PR DESCRIPTION
**Pull request by Zehir**
Cakephp allows adding classes like this;
$this->Form->button("Login", ['class'=>['foo','bar']])

But with your plugin that is not possible.
 $this->Form->button("Login", ['bootstrap-type' => 'success','class'=>['foo','bar']])
You can also do this:
 $this->Form->button("Login", ['bootstrap-type' => 'success','class'=>['foo bar']])
Or:
 $this->Form->button("Login", ['bootstrap-type' => 'success','class'=>'foo bar'])

Now with this fix this work.

### CODE REVIEW

**Comment by Holt59** [comment]
Thanks for the (awesome) update!

**Comment by Holt59** [comment]
Well, I had to rollback to a previous commit since this broke a lot of stuff actually...

**Comment by Holt59** [comment]
I created a fix using a overloaded version of `Helper::addClass` which seems to work.

**Comment by Zehir** [comment]
OK, I just tested for button. Thank

**Comment by Zehir** [comment]
Composer does not download the update, there is a delay?

**Comment by Holt59** [comment]
I forced the update on Packagist so you probably need to clear your composer cache (I often have the same issue... ).

**Comment by Zehir** [comment]
OK this work now thank

**Pull request merged**
